apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster
  labels:
    app: taskmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmaster
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -zv mongo 27017; do echo waiting for mongo; sleep 5; done;']
      containers:
        - name: taskmaster
          image: kunalgohrani/microservicespythonapp:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

